Support Halpe26 keypoints.
Tau-J/rtmlib pull request #25
Opened 2024-06-27 04:07 UTC by hunminkim98

Dear @Tau-J.

Hi, first of all, thank you so much for your awesome work!
My name is Hunmin Kim and I'm interested in markerless motion capture and biomechanics.

I think Halpe26 keypoints are useful in the field of biomechanics. 
So I wanted to implement something that supports Halpe26 in rtmlib, and here is the result!

I hope this works, and I hope you will consider this request.
Thank you.

Best regard.
HunMin Kim

2024-06-28 11:00 UTC, davidpagnon commented
Perfect timing @hunminkim98 ! (it almost looks like we work together :D ) -> Related to https://github.com/Tau-J/rtmlib/issues/24, which I am now closing.

2024-07-01 03:38 UTC, Tau-J requested changes
Thanks for your kind contribution! I have provided some suggestions on naming conventions. Please consider revising your PR to maintain stylistic consistency with the existing code in rtmlib.

2024-07-01 03:38 UTC, Tau-J commented on rtmlib/tools/solution/body_and_feet.py
> +class Body_and_Feet:
Also, the python file should be renamed as `body_with_feet.py`.

2024-07-01 03:40 UTC, Tau-J commented
`body+feet_demo.py` should be renamed as `body_with_feet_demo.py`.

2024-07-01 09:49 UTC, hunminkim98 commented
Hello,
I appreciate your consideration and suggestion!
I changed the names to fit your suggestions. I hope everything meets your expectations.

2024-07-02 06:08 UTC, Tau-J requested changes
Fixed some links

2024-07-02 06:08 UTC, Tau-J commented on README.md
> +  - [Body_and_feet](/rtmlib/tools/solution/body_and_feet.py)
```suggestion
  - [Body_with_feet](/rtmlib/tools/solution/body_with_feet.py)
```

2024-07-02 06:08 UTC, Tau-J commented on README.md
> +| [RTMPose-x](https://github.com/open-mmlab/mmpose/blob/dev-1.x/projects/rtmpose/rtmpose/body_2d_keypoint/rtmpose-x_8xb256-700e_body8-halpe26-384x288.py) |  384x288   |   74.82    | trained on 7 data
```suggestion
| [RTMPose-l](https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/onnx_sdk/rtmpose-l_simcc-body7_pt-body7-halpe26_700e-256x192-2abb7558_20230605.zip) |  256x192   |   73.19    | trained on 7 datasets |
| [RTMPose-m](https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/onnx_sdk/rtmpose-m_simcc-body7_pt-body7-halpe26_700e-384x288-89e6428b_20230605.zip) |  384x288   |   73.56    | trained on 7 datasets |
| [RTMPose-l](https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/onnx_sdk/rtmpose-l_simcc-body7_pt-body7-halpe26_700e-384x288-734182ce_20230605.zip) |  384x288   |   74.38    | trained on 7 datasets |
| [RTMPose-x](https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/onnx_sdk/rtmpose-x_simcc-body7_pt-body7-halpe26_700e-384x288-7fb6e239_20230606.zip) |  384x288   |   74.82    | trained on 7 datasets |
```

2024-07-03 05:36 UTC, Tau-J approved these changes
LGTM

2024-07-03 05:36 UTC, merged

2024-07-03 06:14 UTC, hunminkim98 commented
Thanks for the approval and thanks again for your work🙏.